//! Build D runtime + std (phobos) using zig-build with ABS
const std = @import("std");
const ldc2 = @import("abs").ldc2;
const zcc = @import("abs").zcc;
const builtin = @import("builtin");

pub fn build(b: *std.Build) !void {
    // ldc2/ldmd2 not have mingw-support
    const target = b.standardTargetOptions(.{
        .default_target = if (builtin.os.tag == .windows)
            try std.Target.Query.parse(.{
                .arch_os_abi = "native-windows-msvc",
            })
        else
            .{},
    });
    const optimize = b.standardOptimizeOption(.{});

    const linkMode = b.option(std.builtin.LinkMode, "linkage", "Change linking mode (default: static)") orelse .static;
    const enable_phobos = b.option(bool, "phobos", "Build phobos library (default: false)") orelse false;

    try buildRuntime(b, .{
        .target = target,
        .optimize = optimize,
        .linkage = linkMode,
    });
    if (enable_phobos)
        try buildPhobos(b, .{
            .target = target,
            .optimize = optimize,
            .linkage = linkMode,
            .dependency = b.dependency("phobos", .{}),
        });
}

fn buildRuntime(b: *std.Build, options: buildOptions) !void {
    const source = switch (options.target.result.os.tag) {
        .windows => runtime_src ++ &[_][]const u8{
            "druntime/src/ldc/eh_msvc.d",
            "druntime/src/ldc/msvc.c",
        },
        else => runtime_src,
    };

    const complementary = b.addStaticLibrary(.{
        .name = "asm",
        .target = options.target,
        .optimize = options.optimize,
    });
    complementary.addAssemblyFile(b.path("druntime/src/core/threadasm.S"));
    complementary.addAssemblyFile(b.path("druntime/src/ldc/eh_asm.S"));
    if (options.target.result.cpu.arch.isAARCH64()) {
        complementary.addCSourceFile(.{
            .file = b.path("druntime/src/ldc/arm_unwind.c"),
        });
        complementary.linkLibC();
    }
    if (options.target.result.os.tag == .linux) {
        complementary.addCSourceFile(.{
            .file = b.path("druntime/src/core/stdc/errno.c"),
        });
        complementary.linkLibC();
    }
    if (options.target.result.os.tag == .macos) {
        complementary.addCSourceFile(.{
            .file = b.path("druntime/src/rt/dylib_fixes.c"),
        });
        complementary.linkLibC();
    }
    const versions_config = switch (options.target.result.cpu.arch) {
        .aarch64, .x86_64, .x86 => &[_][]const u8{
            "AsmExternal", // used by fiber module
            "OnlyLowMemUnittest", // disables memory-greedy unittests
            "SupportSanitizers", // enables sanitizers support
        },
        else => &[_][]const u8{
            "OnlyLowMemUnittest", // disables memory-greedy unittests
            "SupportSanitizers", // enables sanitizers support
        },
    };

    const tagLabel = switch (options.optimize) {
        .Debug => "-debug",
        else => "",
    };
    const linkMode = switch (options.linkage) {
        .static => "-static",
        .dynamic => "-shared",
    };
    try buildD(b, .{
        .name = b.fmt("druntime-ldc{s}{s}", .{
            tagLabel,
            linkMode,
        }),
        .kind = .lib,
        .linkage = options.linkage,
        .target = options.target,
        .optimize = options.optimize,
        .sources = source,
        .dflags = &.{
            "-w",
            "-de",
            "-preview=dip1000",
            "-preview=dtorfields",
            "-preview=fieldwise",
            "-conf=",
            "-defaultlib=",
            "-debuglib=",
        },
        .importPaths = &.{
            "druntime/src",
        },
        .cIncludePaths = &.{
            "druntime/src", // importc header
        },
        .versions = versions_config,
        .artifact = complementary,
        .use_zigcc = true,
        .zcc_options = try zcc.buildOptions(b, options.target),
    });
}

fn buildD(b: *std.Build, options: ldc2.DCompileStep) !void {
    const exe = try ldc2.BuildStep(b, options);
    b.default_step.dependOn(&exe.step);
}

fn buildPhobos(b: *std.Build, options: buildOptions) !void {
    const phobos_path = if (options.dependency) |dep|
        dep.path("").getPath(b)
    else
        unreachable;
    const tagLabel = switch (options.optimize) {
        .Debug => "-debug",
        else => "",
    };
    const linkMode = switch (options.linkage) {
        .static => "-static",
        .dynamic => "-shared",
    };
    try buildD(b, .{
        .name = b.fmt("phobos2-ldc{s}{s}", .{
            tagLabel,
            linkMode,
        }),
        .kind = .lib,
        .linkage = options.linkage,
        .target = options.target,
        .optimize = options.optimize,
        .sources = &[_][]const u8{
            b.pathJoin(&.{ phobos_path, "etc/c/curl.d" }),
            b.pathJoin(&.{ phobos_path, "etc/c/odbc/sql.d" }),
            b.pathJoin(&.{ phobos_path, "etc/c/odbc/sqlext.d" }),
            b.pathJoin(&.{ phobos_path, "etc/c/odbc/sqltypes.d" }),
            b.pathJoin(&.{ phobos_path, "etc/c/odbc/sqlucode.d" }),
            b.pathJoin(&.{ phobos_path, "etc/c/sqlite3.d" }),
            b.pathJoin(&.{ phobos_path, "etc/c/zlib.d" }),
            b.pathJoin(&.{ phobos_path, "phobos/sys/compiler.d" }),
            b.pathJoin(&.{ phobos_path, "phobos/sys/meta.d" }),
            b.pathJoin(&.{ phobos_path, "phobos/sys/system.d" }),
            b.pathJoin(&.{ phobos_path, "phobos/sys/traits.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/comparison.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/internal.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/iteration.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/mutation.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/searching.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/setops.d" }),
            b.pathJoin(&.{ phobos_path, "std/algorithm/sorting.d" }),
            b.pathJoin(&.{ phobos_path, "std/array.d" }),
            b.pathJoin(&.{ phobos_path, "std/ascii.d" }),
            b.pathJoin(&.{ phobos_path, "std/base64.d" }),
            b.pathJoin(&.{ phobos_path, "std/bigint.d" }),
            b.pathJoin(&.{ phobos_path, "std/bitmanip.d" }),
            b.pathJoin(&.{ phobos_path, "std/checkedint.d" }),
            b.pathJoin(&.{ phobos_path, "std/compiler.d" }),
            b.pathJoin(&.{ phobos_path, "std/complex.d" }),
            b.pathJoin(&.{ phobos_path, "std/concurrency.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/array.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/binaryheap.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/dlist.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/rbtree.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/slist.d" }),
            b.pathJoin(&.{ phobos_path, "std/container/util.d" }),
            b.pathJoin(&.{ phobos_path, "std/conv.d" }),
            b.pathJoin(&.{ phobos_path, "std/csv.d" }),
            b.pathJoin(&.{ phobos_path, "std/datetime/date.d" }),
            b.pathJoin(&.{ phobos_path, "std/datetime/interval.d" }),
            b.pathJoin(&.{ phobos_path, "std/datetime/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/datetime/stopwatch.d" }),
            b.pathJoin(&.{ phobos_path, "std/datetime/systime.d" }),
            b.pathJoin(&.{ phobos_path, "std/datetime/timezone.d" }),
            b.pathJoin(&.{ phobos_path, "std/demangle.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/crc.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/hmac.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/md.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/murmurhash.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/ripemd.d" }),
            b.pathJoin(&.{ phobos_path, "std/digest/sha.d" }),
            b.pathJoin(&.{ phobos_path, "std/encoding.d" }),
            b.pathJoin(&.{ phobos_path, "std/exception.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/affix_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/aligned_block_list.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/allocator_list.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/ascending_page_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/bitmapped_block.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/bucketizer.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/fallback_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/free_list.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/free_tree.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/kernighan_ritchie.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/null_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/quantizer.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/region.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/scoped_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/segregator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/building_blocks/stats_collector.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/common.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/gc_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/mallocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/mmap_allocator.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/showcase.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/allocator/typed.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/checkedint.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/logger/core.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/logger/filelogger.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/logger/multilogger.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/logger/nulllogger.d" }),
            b.pathJoin(&.{ phobos_path, "std/experimental/logger/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/file.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/internal/floats.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/internal/read.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/internal/write.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/read.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/spec.d" }),
            b.pathJoin(&.{ phobos_path, "std/format/write.d" }),
            b.pathJoin(&.{ phobos_path, "std/functional.d" }),
            b.pathJoin(&.{ phobos_path, "std/getopt.d" }),
            b.pathJoin(&.{ phobos_path, "std/int128.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/attributes.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/cstring.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/digest/sha_SSSE3.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/math/biguintarm.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/math/biguintcore.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/math/biguintnoasm.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/math/biguintx86.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/math/errorfunction.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/math/gammafunction.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/memory.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/scopebuffer.d" }),
            // b.pathJoin(&.{phobos_path, "std/internal/test/dummyrange.d"}),
            // b.pathJoin(&.{phobos_path, "std/internal/test/range.d"}),
            // b.pathJoin(&.{phobos_path, "std/internal/test/uda.d"}),
            b.pathJoin(&.{ phobos_path, "std/internal/unicode_comp.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/unicode_decomp.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/unicode_grapheme.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/unicode_norm.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/unicode_tables.d" }),
            b.pathJoin(&.{ phobos_path, "std/internal/windows/advapi32.d" }),
            b.pathJoin(&.{ phobos_path, "std/json.d" }),
            b.pathJoin(&.{ phobos_path, "std/logger/core.d" }),
            b.pathJoin(&.{ phobos_path, "std/logger/filelogger.d" }),
            b.pathJoin(&.{ phobos_path, "std/logger/multilogger.d" }),
            b.pathJoin(&.{ phobos_path, "std/logger/nulllogger.d" }),
            b.pathJoin(&.{ phobos_path, "std/logger/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/algebraic.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/constants.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/exponential.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/hardware.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/operations.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/remainder.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/rounding.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/traits.d" }),
            b.pathJoin(&.{ phobos_path, "std/math/trigonometry.d" }),
            b.pathJoin(&.{ phobos_path, "std/mathspecial.d" }),
            b.pathJoin(&.{ phobos_path, "std/meta.d" }),
            b.pathJoin(&.{ phobos_path, "std/mmfile.d" }),
            b.pathJoin(&.{ phobos_path, "std/net/curl.d" }),
            b.pathJoin(&.{ phobos_path, "std/net/isemail.d" }),
            b.pathJoin(&.{ phobos_path, "std/numeric.d" }),
            b.pathJoin(&.{ phobos_path, "std/outbuffer.d" }),
            b.pathJoin(&.{ phobos_path, "std/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/parallelism.d" }),
            b.pathJoin(&.{ phobos_path, "std/path.d" }),
            b.pathJoin(&.{ phobos_path, "std/process.d" }),
            b.pathJoin(&.{ phobos_path, "std/random.d" }),
            b.pathJoin(&.{ phobos_path, "std/range/interfaces.d" }),
            b.pathJoin(&.{ phobos_path, "std/range/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/range/primitives.d" }),
            b.pathJoin(&.{ phobos_path, "std/regex/internal/backtracking.d" }),
            b.pathJoin(&.{ phobos_path, "std/regex/internal/generator.d" }),
            b.pathJoin(&.{ phobos_path, "std/regex/internal/ir.d" }),
            b.pathJoin(&.{ phobos_path, "std/regex/internal/kickstart.d" }),
            b.pathJoin(&.{ phobos_path, "std/regex/internal/parser.d" }),
            // b.pathJoin(&.{phobos_path, "std/regex/internal/tests.d"}),
            // b.pathJoin(&.{phobos_path, "std/regex/internal/tests2.d"}),
            b.pathJoin(&.{ phobos_path, "std/regex/internal/thompson.d" }),
            b.pathJoin(&.{ phobos_path, "std/regex/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/signals.d" }),
            b.pathJoin(&.{ phobos_path, "std/socket.d" }),
            b.pathJoin(&.{ phobos_path, "std/stdint.d" }),
            b.pathJoin(&.{ phobos_path, "std/stdio.d" }),
            b.pathJoin(&.{ phobos_path, "std/string.d" }),
            b.pathJoin(&.{ phobos_path, "std/sumtype.d" }),
            b.pathJoin(&.{ phobos_path, "std/system.d" }),
            b.pathJoin(&.{ phobos_path, "std/traits.d" }),
            b.pathJoin(&.{ phobos_path, "std/typecons.d" }),
            b.pathJoin(&.{ phobos_path, "std/typetuple.d" }),
            b.pathJoin(&.{ phobos_path, "std/uni/package.d" }),
            b.pathJoin(&.{ phobos_path, "std/uri.d" }),
            b.pathJoin(&.{ phobos_path, "std/utf.d" }),
            b.pathJoin(&.{ phobos_path, "std/uuid.d" }),
            b.pathJoin(&.{ phobos_path, "std/variant.d" }),
            b.pathJoin(&.{ phobos_path, "std/windows/charset.d" }),
            b.pathJoin(&.{ phobos_path, "std/windows/registry.d" }),
            b.pathJoin(&.{ phobos_path, "std/windows/syserror.d" }),
            b.pathJoin(&.{ phobos_path, "std/zip.d" }),
            b.pathJoin(&.{ phobos_path, "std/zlib.d" }),
            // b.pathJoin(&.{phobos_path, "test/betterc_module_tests.d"}),
            // b.pathJoin(&.{phobos_path, "test/dub_stdx_allocator.d"}),
            // b.pathJoin(&.{phobos_path, "test/dub_stdx_checkedint.d"}),
            b.pathJoin(&.{ phobos_path, "tools/unicode_table_generator.d" }),
            // b.pathJoin(&.{phobos_path, "unittest.d"}),
        },
        .dflags = &.{
            "-w",
            "-conf=",
            "-defaultlib=",
            "-debuglib=",
            "-de",
            "-preview=dip1000",
            "-preview=dtorfields",
            "-preview=fieldwise",
            "-lowmem",
            b.fmt("-L-L{s}", .{b.path("zig-out/lib").getPath(b)}),
            b.fmt("-L-ldruntime-ldc{s}{s}", .{
                tagLabel,
                linkMode,
            }),
        },
        .importPaths = &.{
            phobos_path,
            "druntime/src",
        },
        .cIncludePaths = &.{
            "druntime/src",
        },
        .artifact = buildZlib(b, options),
        .use_zigcc = true,
        .zcc_options = try zcc.buildOptions(b, options.target),
    });
}

const buildOptions = struct {
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    linkage: std.builtin.LinkMode = .static,
    dependency: ?*std.Build.Dependency = null,
};

const runtime_src = &[_][]const u8{
    "druntime/src/core/atomic.d",
    "druntime/src/core/attribute.d",
    "druntime/src/core/bitop.d",
    "druntime/src/core/builtins.d",
    "druntime/src/core/cpuid.d",
    "druntime/src/core/exception.d",
    "druntime/src/core/factory.d",
    "druntime/src/core/gc/config.d",
    "druntime/src/core/gc/gcinterface.d",
    "druntime/src/core/gc/registry.d",
    "druntime/src/core/int128.d",
    "druntime/src/core/internal/abort.d",
    "druntime/src/core/internal/array/appending.d",
    "druntime/src/core/internal/array/arrayassign.d",
    "druntime/src/core/internal/array/capacity.d",
    "druntime/src/core/internal/array/casting.d",
    "druntime/src/core/internal/array/comparison.d",
    "druntime/src/core/internal/array/concatenation.d",
    "druntime/src/core/internal/array/construction.d",
    "druntime/src/core/internal/array/duplication.d",
    "druntime/src/core/internal/array/equality.d",
    "druntime/src/core/internal/array/operations.d",
    "druntime/src/core/internal/array/utils.d",
    "druntime/src/core/internal/atomic.d",
    "druntime/src/core/internal/attributes.d",
    "druntime/src/core/internal/backtrace/dwarf.d",
    "druntime/src/core/internal/backtrace/elf.d",
    "druntime/src/core/internal/backtrace/handler.d",
    "druntime/src/core/internal/backtrace/macho.d",
    "druntime/src/core/internal/backtrace/unwind.d",
    "druntime/src/core/internal/backtrace/libunwind.d",
    "druntime/src/core/internal/container/array.d",
    "druntime/src/core/internal/container/common.d",
    "druntime/src/core/internal/container/hashtab.d",
    "druntime/src/core/internal/container/treap.d",
    "druntime/src/core/internal/convert.d",
    "druntime/src/core/internal/dassert.d",
    "druntime/src/core/internal/destruction.d",
    "druntime/src/core/internal/elf/dl.d",
    "druntime/src/core/internal/elf/io.d",
    "druntime/src/core/internal/entrypoint.d",
    "druntime/src/core/internal/execinfo.d",
    "druntime/src/core/internal/gc/bits.d",
    "druntime/src/core/internal/gc/impl/conservative/gc.d",
    "druntime/src/core/internal/gc/impl/manual/gc.d",
    "druntime/src/core/internal/gc/impl/proto/gc.d",
    "druntime/src/core/internal/gc/os.d",
    "druntime/src/core/internal/gc/pooltable.d",
    "druntime/src/core/internal/gc/proxy.d",
    "druntime/src/core/internal/hash.d",
    "druntime/src/core/internal/lifetime.d",
    "druntime/src/core/internal/moving.d",
    "druntime/src/core/internal/postblit.d",
    "druntime/src/core/internal/qsort.d",
    "druntime/src/core/internal/spinlock.d",
    "druntime/src/core/internal/string.d",
    "druntime/src/core/internal/switch_.d",
    "druntime/src/core/internal/utf.d",
    "druntime/src/core/internal/util/array.d",
    "druntime/src/core/internal/util/math.d",
    "druntime/src/core/internal/vararg/aarch64.d",
    "druntime/src/core/internal/vararg/sysv_x64.d",
    "druntime/src/core/internal/newaa.d",
    "druntime/src/core/internal/parseoptions.d",
    "druntime/src/core/internal/traits.d",
    "druntime/src/core/interpolation.d",
    "druntime/src/core/math.d",
    "druntime/src/core/memory.d",
    "druntime/src/core/simd.d",
    "druntime/src/core/stdc/complex.d",
    "druntime/src/core/stdc/config.d",
    "druntime/src/core/stdc/ctype.d",
    "druntime/src/core/stdc/float_.d",
    "druntime/src/core/stdc/inttypes.d",
    "druntime/src/core/stdc/limits.d",
    "druntime/src/core/stdc/locale.d",
    "druntime/src/core/stdc/signal.d",
    "druntime/src/core/stdc/stdarg.d",
    "druntime/src/core/stdc/stdatomic.d",
    "druntime/src/core/stdc/stddef.d",
    "druntime/src/core/stdc/stdlib.d",
    "druntime/src/core/stdc/string.d",
    "druntime/src/core/stdc/tgmath.d",
    "druntime/src/core/stdc/time.d",
    "druntime/src/core/stdc/wchar_.d",
    "druntime/src/core/stdc/wctype.d",
    "druntime/src/core/stdc/assert_.d",
    "druntime/src/core/stdc/errno.d",
    "druntime/src/core/stdc/fenv.d",
    "druntime/src/core/stdc/math.d",
    "druntime/src/core/stdc/stdint.d",
    "druntime/src/core/stdc/stdio.d",
    "druntime/src/core/stdcpp/type_traits.d",
    "druntime/src/core/stdcpp/utility.d",
    "druntime/src/core/stdcpp/vector.d",
    "druntime/src/core/stdcpp/allocator.d",
    "druntime/src/core/stdcpp/array.d",
    "druntime/src/core/stdcpp/exception.d",
    "druntime/src/core/stdcpp/memory.d",
    "druntime/src/core/stdcpp/new_.d",
    "druntime/src/core/stdcpp/string.d",
    "druntime/src/core/stdcpp/string_view.d",
    "druntime/src/core/stdcpp/typeinfo.d",
    "druntime/src/core/stdcpp/xutility.d",
    "druntime/src/core/sync/barrier.d",
    "druntime/src/core/sync/condition.d",
    "druntime/src/core/sync/config.d",
    "druntime/src/core/sync/event.d",
    "druntime/src/core/sync/exception.d",
    "druntime/src/core/sync/mutex.d",
    "druntime/src/core/sync/package.d",
    "druntime/src/core/sync/rwmutex.d",
    "druntime/src/core/sync/semaphore.d",
    "druntime/src/core/sys/bionic/err.d",
    "druntime/src/core/sys/bionic/fcntl.d",
    "druntime/src/core/sys/bionic/stdlib.d",
    "druntime/src/core/sys/bionic/string.d",
    "druntime/src/core/sys/bionic/unistd.d",
    "druntime/src/core/sys/darwin/crt_externs.d",
    "druntime/src/core/sys/darwin/dlfcn.d",
    "druntime/src/core/sys/darwin/err.d",
    "druntime/src/core/sys/darwin/execinfo.d",
    "druntime/src/core/sys/darwin/fcntl.d",
    "druntime/src/core/sys/darwin/ifaddrs.d",
    "druntime/src/core/sys/darwin/mach/dyld.d",
    "druntime/src/core/sys/darwin/mach/getsect.d",
    "druntime/src/core/sys/darwin/mach/kern_return.d",
    "druntime/src/core/sys/darwin/mach/loader.d",
    "druntime/src/core/sys/darwin/mach/nlist.d",
    "druntime/src/core/sys/darwin/mach/port.d",
    "druntime/src/core/sys/darwin/mach/semaphore.d",
    "druntime/src/core/sys/darwin/mach/stab.d",
    "druntime/src/core/sys/darwin/mach/thread_act.d",
    // "druntime/src/core/sys/darwin/netinet/in_.d",
    "druntime/src/core/sys/darwin/pthread.d",
    "druntime/src/core/sys/darwin/stdlib.d",
    "druntime/src/core/sys/darwin/string.d",
    "druntime/src/core/sys/darwin/sys/attr.d",
    "druntime/src/core/sys/darwin/sys/cdefs.d",
    "druntime/src/core/sys/darwin/sys/event.d",
    "druntime/src/core/sys/darwin/sys/mman.d",
    "druntime/src/core/sys/darwin/sys/sysctl.d",
    "druntime/src/core/sys/dragonflybsd/dlfcn.d",
    "druntime/src/core/sys/dragonflybsd/err.d",
    "druntime/src/core/sys/dragonflybsd/execinfo.d",
    "druntime/src/core/sys/dragonflybsd/netinet/in_.d",
    "druntime/src/core/sys/dragonflybsd/pthread_np.d",
    "druntime/src/core/sys/dragonflybsd/stdlib.d",
    "druntime/src/core/sys/dragonflybsd/string.d",
    "druntime/src/core/sys/dragonflybsd/sys/_bitset.d",
    "druntime/src/core/sys/dragonflybsd/sys/_cpuset.d",
    "druntime/src/core/sys/dragonflybsd/sys/cdefs.d",
    "druntime/src/core/sys/dragonflybsd/sys/elf.d",
    "druntime/src/core/sys/dragonflybsd/sys/elf32.d",
    "druntime/src/core/sys/dragonflybsd/sys/elf64.d",
    "druntime/src/core/sys/dragonflybsd/sys/elf_common.d",
    "druntime/src/core/sys/dragonflybsd/sys/event.d",
    "druntime/src/core/sys/dragonflybsd/sys/link_elf.d",
    "druntime/src/core/sys/dragonflybsd/sys/mman.d",
    "druntime/src/core/sys/dragonflybsd/sys/socket.d",
    "druntime/src/core/sys/dragonflybsd/sys/sysctl.d",
    "druntime/src/core/sys/dragonflybsd/time.d",
    "druntime/src/core/sys/elf/package.d",
    "druntime/src/core/sys/freebsd/config.d",
    "druntime/src/core/sys/freebsd/dlfcn.d",
    "druntime/src/core/sys/freebsd/err.d",
    "druntime/src/core/sys/freebsd/execinfo.d",
    "druntime/src/core/sys/freebsd/ifaddrs.d",
    "druntime/src/core/sys/freebsd/mqueue.d",
    "druntime/src/core/sys/freebsd/net/if_.d",
    "druntime/src/core/sys/freebsd/net/if_dl.d",
    "druntime/src/core/sys/freebsd/netinet/in_.d",
    "druntime/src/core/sys/freebsd/pthread_np.d",
    "druntime/src/core/sys/freebsd/stdlib.d",
    "druntime/src/core/sys/freebsd/string.d",
    "druntime/src/core/sys/freebsd/sys/_bitset.d",
    "druntime/src/core/sys/freebsd/sys/_cpuset.d",
    "druntime/src/core/sys/freebsd/sys/cdefs.d",
    "druntime/src/core/sys/freebsd/sys/elf.d",
    "druntime/src/core/sys/freebsd/sys/elf32.d",
    "druntime/src/core/sys/freebsd/sys/elf64.d",
    "druntime/src/core/sys/freebsd/sys/elf_common.d",
    "druntime/src/core/sys/freebsd/sys/event.d",
    "druntime/src/core/sys/freebsd/sys/link_elf.d",
    "druntime/src/core/sys/freebsd/sys/mman.d",
    "druntime/src/core/sys/freebsd/sys/mount.d",
    "druntime/src/core/sys/freebsd/sys/socket.d",
    "druntime/src/core/sys/freebsd/sys/sysctl.d",
    "druntime/src/core/sys/freebsd/sys/types.d",
    "druntime/src/core/sys/freebsd/time.d",
    "druntime/src/core/sys/freebsd/unistd.d",
    "druntime/src/core/sys/linux/config.d",
    "druntime/src/core/sys/linux/dlfcn.d",
    "druntime/src/core/sys/linux/elf.d",
    "druntime/src/core/sys/linux/epoll.d",
    "druntime/src/core/sys/linux/err.d",
    "druntime/src/core/sys/linux/errno.d",
    "druntime/src/core/sys/linux/execinfo.d",
    "druntime/src/core/sys/linux/fcntl.d",
    "druntime/src/core/sys/linux/fs.d",
    "druntime/src/core/sys/linux/ifaddrs.d",
    "druntime/src/core/sys/linux/input.d",
    "druntime/src/core/sys/linux/input_event_codes.d",
    "druntime/src/core/sys/linux/io_uring.d",
    "druntime/src/core/sys/linux/link.d",
    "druntime/src/core/sys/linux/linux/if_arp.d",
    "druntime/src/core/sys/linux/linux/if_packet.d",
    "druntime/src/core/sys/linux/netinet/in_.d",
    "druntime/src/core/sys/linux/netinet/tcp.d",
    "druntime/src/core/sys/linux/perf_event.d",
    "druntime/src/core/sys/linux/sched.d",
    "druntime/src/core/sys/linux/stdio.d",
    "druntime/src/core/sys/linux/string.d",
    "druntime/src/core/sys/linux/sys/auxv.d",
    "druntime/src/core/sys/linux/sys/eventfd.d",
    "druntime/src/core/sys/linux/sys/file.d",
    "druntime/src/core/sys/linux/sys/inotify.d",
    "druntime/src/core/sys/linux/sys/mman.d",
    "druntime/src/core/sys/linux/sys/mount.d",
    "druntime/src/core/sys/linux/sys/prctl.d",
    "druntime/src/core/sys/linux/sys/procfs.d",
    "druntime/src/core/sys/linux/sys/signalfd.d",
    "druntime/src/core/sys/linux/sys/socket.d",
    "druntime/src/core/sys/linux/sys/sysinfo.d",
    "druntime/src/core/sys/linux/sys/time.d",
    "druntime/src/core/sys/linux/sys/xattr.d",
    "druntime/src/core/sys/linux/termios.d",
    "druntime/src/core/sys/linux/time.d",
    "druntime/src/core/sys/linux/timerfd.d",
    "druntime/src/core/sys/linux/tipc.d",
    "druntime/src/core/sys/linux/uinput.d",
    "druntime/src/core/sys/linux/unistd.d",
    "druntime/src/core/sys/netbsd/dlfcn.d",
    "druntime/src/core/sys/netbsd/err.d",
    "druntime/src/core/sys/netbsd/execinfo.d",
    "druntime/src/core/sys/netbsd/stdlib.d",
    "druntime/src/core/sys/netbsd/string.d",
    "druntime/src/core/sys/netbsd/sys/elf.d",
    "druntime/src/core/sys/netbsd/sys/elf32.d",
    "druntime/src/core/sys/netbsd/sys/elf64.d",
    "druntime/src/core/sys/netbsd/sys/elf_common.d",
    "druntime/src/core/sys/netbsd/sys/event.d",
    "druntime/src/core/sys/netbsd/sys/featuretest.d",
    "druntime/src/core/sys/netbsd/sys/link_elf.d",
    "druntime/src/core/sys/netbsd/sys/mman.d",
    "druntime/src/core/sys/netbsd/sys/sysctl.d",
    "druntime/src/core/sys/netbsd/time.d",
    "druntime/src/core/sys/openbsd/dlfcn.d",
    "druntime/src/core/sys/openbsd/err.d",
    "druntime/src/core/sys/openbsd/execinfo.d",
    "druntime/src/core/sys/openbsd/pthread_np.d",
    "druntime/src/core/sys/openbsd/pwd.d",
    "druntime/src/core/sys/openbsd/stdlib.d",
    "druntime/src/core/sys/openbsd/string.d",
    "druntime/src/core/sys/openbsd/sys/cdefs.d",
    "druntime/src/core/sys/openbsd/sys/elf.d",
    "druntime/src/core/sys/openbsd/sys/elf32.d",
    "druntime/src/core/sys/openbsd/sys/elf64.d",
    "druntime/src/core/sys/openbsd/sys/elf_common.d",
    "druntime/src/core/sys/openbsd/sys/link_elf.d",
    "druntime/src/core/sys/openbsd/sys/mman.d",
    "druntime/src/core/sys/openbsd/sys/sysctl.d",
    "druntime/src/core/sys/openbsd/time.d",
    "druntime/src/core/sys/openbsd/unistd.d",
    "druntime/src/core/sys/posix/aio.d",
    "druntime/src/core/sys/posix/arpa/inet.d",
    "druntime/src/core/sys/posix/config.d",
    "druntime/src/core/sys/posix/dlfcn.d",
    "druntime/src/core/sys/posix/fcntl.d",
    "druntime/src/core/sys/posix/grp.d",
    "druntime/src/core/sys/posix/iconv.d",
    "druntime/src/core/sys/posix/inttypes.d",
    "druntime/src/core/sys/posix/libgen.d",
    "druntime/src/core/sys/posix/locale.d",
    "druntime/src/core/sys/posix/mqueue.d",
    "druntime/src/core/sys/posix/net/if_.d",
    "druntime/src/core/sys/posix/netdb.d",
    "druntime/src/core/sys/posix/netinet/in_.d",
    "druntime/src/core/sys/posix/netinet/tcp.d",
    "druntime/src/core/sys/posix/poll.d",
    "druntime/src/core/sys/posix/pthread.d",
    "druntime/src/core/sys/posix/pwd.d",
    "druntime/src/core/sys/posix/sched.d",
    "druntime/src/core/sys/posix/semaphore.d",
    "druntime/src/core/sys/posix/setjmp.d",
    "druntime/src/core/sys/posix/signal.d",
    "druntime/src/core/sys/posix/spawn.d",
    "druntime/src/core/sys/posix/stdc/time.d",
    "druntime/src/core/sys/posix/stdio.d",
    "druntime/src/core/sys/posix/stdlib.d",
    "druntime/src/core/sys/posix/string.d",
    "druntime/src/core/sys/posix/strings.d",
    "druntime/src/core/sys/posix/sys/filio.d",
    "druntime/src/core/sys/posix/sys/ioccom.d",
    "druntime/src/core/sys/posix/sys/ioctl.d",
    "druntime/src/core/sys/posix/sys/ipc.d",
    "druntime/src/core/sys/posix/sys/mman.d",
    "druntime/src/core/sys/posix/sys/msg.d",
    "druntime/src/core/sys/posix/sys/resource.d",
    "druntime/src/core/sys/posix/sys/select.d",
    "druntime/src/core/sys/posix/sys/shm.d",
    "druntime/src/core/sys/posix/sys/socket.d",
    "druntime/src/core/sys/posix/sys/statvfs.d",
    "druntime/src/core/sys/posix/sys/time.d",
    "druntime/src/core/sys/posix/sys/ttycom.d",
    "druntime/src/core/sys/posix/sys/types.d",
    "druntime/src/core/sys/posix/sys/uio.d",
    "druntime/src/core/sys/posix/sys/un.d",
    "druntime/src/core/sys/posix/sys/utsname.d",
    "druntime/src/core/sys/posix/sys/wait.d",
    "druntime/src/core/sys/posix/sys/stat.d",
    "druntime/src/core/sys/posix/syslog.d",
    "druntime/src/core/sys/posix/termios.d",
    "druntime/src/core/sys/posix/time.d",
    "druntime/src/core/sys/posix/ucontext.d",
    "druntime/src/core/sys/posix/unistd.d",
    "druntime/src/core/sys/posix/utime.d",
    "druntime/src/core/sys/posix/dirent.d",
    "druntime/src/core/sys/solaris/dlfcn.d",
    "druntime/src/core/sys/solaris/elf.d",
    "druntime/src/core/sys/solaris/err.d",
    "druntime/src/core/sys/solaris/execinfo.d",
    "druntime/src/core/sys/solaris/libelf.d",
    "druntime/src/core/sys/solaris/link.d",
    "druntime/src/core/sys/solaris/stdlib.d",
    "druntime/src/core/sys/solaris/sys/elf.d",
    "druntime/src/core/sys/solaris/sys/elf_386.d",
    "druntime/src/core/sys/solaris/sys/elf_SPARC.d",
    "druntime/src/core/sys/solaris/sys/elf_amd64.d",
    "druntime/src/core/sys/solaris/sys/elf_notes.d",
    "druntime/src/core/sys/solaris/sys/elftypes.d",
    "druntime/src/core/sys/solaris/sys/link.d",
    "druntime/src/core/sys/solaris/sys/priocntl.d",
    "druntime/src/core/sys/solaris/sys/procset.d",
    "druntime/src/core/sys/solaris/sys/types.d",
    "druntime/src/core/sys/solaris/time.d",
    "druntime/src/core/sys/windows/accctrl.d",
    "druntime/src/core/sys/windows/aclapi.d",
    "druntime/src/core/sys/windows/aclui.d",
    "druntime/src/core/sys/windows/basetsd.d",
    "druntime/src/core/sys/windows/basetyps.d",
    "druntime/src/core/sys/windows/cderr.d",
    "druntime/src/core/sys/windows/cguid.d",
    "druntime/src/core/sys/windows/com.d",
    "druntime/src/core/sys/windows/comcat.d",
    "druntime/src/core/sys/windows/commctrl.d",
    "druntime/src/core/sys/windows/commdlg.d",
    "druntime/src/core/sys/windows/core.d",
    "druntime/src/core/sys/windows/cpl.d",
    "druntime/src/core/sys/windows/cplext.d",
    "druntime/src/core/sys/windows/custcntl.d",
    "druntime/src/core/sys/windows/dbghelp.d",
    "druntime/src/core/sys/windows/dbghelp_types.d",
    "druntime/src/core/sys/windows/dbt.d",
    "druntime/src/core/sys/windows/dde.d",
    "druntime/src/core/sys/windows/ddeml.d",
    "druntime/src/core/sys/windows/dhcpcsdk.d",
    "druntime/src/core/sys/windows/dlgs.d",
    "druntime/src/core/sys/windows/docobj.d",
    "druntime/src/core/sys/windows/errorrep.d",
    "druntime/src/core/sys/windows/exdisp.d",
    "druntime/src/core/sys/windows/exdispid.d",
    "druntime/src/core/sys/windows/httpext.d",
    "druntime/src/core/sys/windows/idispids.d",
    "druntime/src/core/sys/windows/imagehlp.d",
    "druntime/src/core/sys/windows/imm.d",
    "druntime/src/core/sys/windows/intshcut.d",
    "druntime/src/core/sys/windows/ipexport.d",
    "druntime/src/core/sys/windows/iphlpapi.d",
    "druntime/src/core/sys/windows/ipifcons.d",
    "druntime/src/core/sys/windows/iprtrmib.d",
    "druntime/src/core/sys/windows/iptypes.d",
    "druntime/src/core/sys/windows/isguids.d",
    "druntime/src/core/sys/windows/lm.d",
    "druntime/src/core/sys/windows/lmaccess.d",
    "druntime/src/core/sys/windows/lmalert.d",
    "druntime/src/core/sys/windows/lmapibuf.d",
    "druntime/src/core/sys/windows/lmat.d",
    "druntime/src/core/sys/windows/lmaudit.d",
    "druntime/src/core/sys/windows/lmbrowsr.d",
    "druntime/src/core/sys/windows/lmchdev.d",
    "druntime/src/core/sys/windows/lmconfig.d",
    "druntime/src/core/sys/windows/lmcons.d",
    "druntime/src/core/sys/windows/lmerr.d",
    "druntime/src/core/sys/windows/lmerrlog.d",
    "druntime/src/core/sys/windows/lmmsg.d",
    "druntime/src/core/sys/windows/lmremutl.d",
    "druntime/src/core/sys/windows/lmrepl.d",
    "druntime/src/core/sys/windows/lmserver.d",
    "druntime/src/core/sys/windows/lmshare.d",
    "druntime/src/core/sys/windows/lmsname.d",
    "druntime/src/core/sys/windows/lmstats.d",
    "druntime/src/core/sys/windows/lmsvc.d",
    "druntime/src/core/sys/windows/lmuse.d",
    "druntime/src/core/sys/windows/lmuseflg.d",
    "druntime/src/core/sys/windows/lmwksta.d",
    "druntime/src/core/sys/windows/lzexpand.d",
    "druntime/src/core/sys/windows/mapi.d",
    "druntime/src/core/sys/windows/mciavi.d",
    "druntime/src/core/sys/windows/mcx.d",
    "druntime/src/core/sys/windows/mgmtapi.d",
    "druntime/src/core/sys/windows/mmsystem.d",
    "druntime/src/core/sys/windows/msacm.d",
    "druntime/src/core/sys/windows/mshtml.d",
    "druntime/src/core/sys/windows/mswsock.d",
    "druntime/src/core/sys/windows/nb30.d",
    "druntime/src/core/sys/windows/nddeapi.d",
    "druntime/src/core/sys/windows/nspapi.d",
    "druntime/src/core/sys/windows/ntdef.d",
    "druntime/src/core/sys/windows/ntdll.d",
    "druntime/src/core/sys/windows/ntldap.d",
    "druntime/src/core/sys/windows/ntsecapi.d",
    "druntime/src/core/sys/windows/ntsecpkg.d",
    "druntime/src/core/sys/windows/oaidl.d",
    "druntime/src/core/sys/windows/objbase.d",
    "druntime/src/core/sys/windows/objfwd.d",
    "druntime/src/core/sys/windows/objidl.d",
    "druntime/src/core/sys/windows/objsafe.d",
    "druntime/src/core/sys/windows/ocidl.d",
    "druntime/src/core/sys/windows/odbcinst.d",
    "druntime/src/core/sys/windows/ole.d",
    "druntime/src/core/sys/windows/ole2.d",
    "druntime/src/core/sys/windows/ole2ver.d",
    "druntime/src/core/sys/windows/oleacc.d",
    "druntime/src/core/sys/windows/oleauto.d",
    "druntime/src/core/sys/windows/olectl.d",
    "druntime/src/core/sys/windows/olectlid.d",
    "druntime/src/core/sys/windows/oledlg.d",
    "druntime/src/core/sys/windows/oleidl.d",
    "druntime/src/core/sys/windows/pbt.d",
    "druntime/src/core/sys/windows/powrprof.d",
    "druntime/src/core/sys/windows/prsht.d",
    "druntime/src/core/sys/windows/psapi.d",
    "druntime/src/core/sys/windows/rapi.d",
    "druntime/src/core/sys/windows/ras.d",
    "druntime/src/core/sys/windows/rasdlg.d",
    "druntime/src/core/sys/windows/raserror.d",
    "druntime/src/core/sys/windows/rassapi.d",
    "druntime/src/core/sys/windows/reason.d",
    "druntime/src/core/sys/windows/regstr.d",
    "druntime/src/core/sys/windows/richedit.d",
    "druntime/src/core/sys/windows/richole.d",
    "druntime/src/core/sys/windows/rpc.d",
    "druntime/src/core/sys/windows/rpcdce.d",
    "druntime/src/core/sys/windows/rpcdce2.d",
    "druntime/src/core/sys/windows/rpcdcep.d",
    "druntime/src/core/sys/windows/rpcndr.d",
    "druntime/src/core/sys/windows/rpcnsi.d",
    "druntime/src/core/sys/windows/rpcnsip.d",
    "druntime/src/core/sys/windows/rpcnterr.d",
    "druntime/src/core/sys/windows/schannel.d",
    "druntime/src/core/sys/windows/sdkddkver.d",
    "druntime/src/core/sys/windows/secext.d",
    "druntime/src/core/sys/windows/security.d",
    "druntime/src/core/sys/windows/servprov.d",
    "druntime/src/core/sys/windows/setupapi.d",
    "druntime/src/core/sys/windows/shellapi.d",
    "druntime/src/core/sys/windows/shldisp.d",
    "druntime/src/core/sys/windows/shlguid.d",
    "druntime/src/core/sys/windows/shlobj.d",
    "druntime/src/core/sys/windows/shlwapi.d",
    "druntime/src/core/sys/windows/snmp.d",
    "druntime/src/core/sys/windows/sql.d",
    "druntime/src/core/sys/windows/sqlext.d",
    "druntime/src/core/sys/windows/sqltypes.d",
    "druntime/src/core/sys/windows/sqlucode.d",
    "druntime/src/core/sys/windows/sspi.d",
    "druntime/src/core/sys/windows/stdc/malloc.d",
    "druntime/src/core/sys/windows/stdc/time.d",
    "druntime/src/core/sys/windows/subauth.d",
    "druntime/src/core/sys/windows/threadaux.d",
    "druntime/src/core/sys/windows/tlhelp32.d",
    "druntime/src/core/sys/windows/tmschema.d",
    "druntime/src/core/sys/windows/unknwn.d",
    "druntime/src/core/sys/windows/uuid.d",
    "druntime/src/core/sys/windows/vfw.d",
    "druntime/src/core/sys/windows/w32api.d",
    "druntime/src/core/sys/windows/winbase.d",
    "druntime/src/core/sys/windows/winber.d",
    "druntime/src/core/sys/windows/wincon.d",
    "druntime/src/core/sys/windows/wincrypt.d",
    "druntime/src/core/sys/windows/windef.d",
    "druntime/src/core/sys/windows/windows.d",
    "druntime/src/core/sys/windows/winerror.d",
    "druntime/src/core/sys/windows/wingdi.d",
    "druntime/src/core/sys/windows/winhttp.d",
    "druntime/src/core/sys/windows/wininet.d",
    "druntime/src/core/sys/windows/winioctl.d",
    "druntime/src/core/sys/windows/winldap.d",
    "druntime/src/core/sys/windows/winnetwk.d",
    "druntime/src/core/sys/windows/winnls.d",
    "druntime/src/core/sys/windows/winnt.d",
    "druntime/src/core/sys/windows/winperf.d",
    "druntime/src/core/sys/windows/winreg.d",
    "druntime/src/core/sys/windows/winsock2.d",
    "druntime/src/core/sys/windows/winspool.d",
    "druntime/src/core/sys/windows/winsvc.d",
    "druntime/src/core/sys/windows/winuser.d",
    "druntime/src/core/sys/windows/winver.d",
    "druntime/src/core/sys/windows/wtsapi32.d",
    "druntime/src/core/sys/windows/wtypes.d",
    "druntime/src/core/sys/windows/dll.d",
    "druntime/src/core/sys/windows/stacktrace.d",
    "druntime/src/core/sys/windows/stat.d",
    "druntime/src/core/thread/context.d",
    "druntime/src/core/thread/fiber.d",
    "druntime/src/core/thread/package.d",
    "druntime/src/core/thread/threadgroup.d",
    "druntime/src/core/thread/types.d",
    "druntime/src/core/thread/osthread.d",
    "druntime/src/core/thread/threadbase.d",
    "druntime/src/core/time.d",
    "druntime/src/core/vararg.d",
    "druntime/src/core/volatile.d",
    "druntime/src/core/checkedint.d",
    "druntime/src/core/demangle.d",
    "druntime/src/core/lifetime.d",
    "druntime/src/core/runtime.d",
    "druntime/src/etc/linux/memoryerror.d",
    "druntime/src/etc/valgrind/valgrind.d",
    "druntime/src/ldc/asan.d",
    "druntime/src/ldc/attributes.d",
    "druntime/src/ldc/dcompute.d",
    "druntime/src/ldc/eh_msvc.d",
    "druntime/src/ldc/sanitizer_common.d",
    "druntime/src/ldc/sanitizers_optionally_linked.d",
    "druntime/src/object.d",
    "druntime/src/rt/aApply.d",
    "druntime/src/rt/aApplyR.d",
    "druntime/src/rt/adi.d",
    "druntime/src/rt/arraycat.d",
    "druntime/src/rt/cast_.d",
    "druntime/src/rt/cmath2.d",
    "druntime/src/rt/config.d",
    "druntime/src/rt/critical_.d",
    "druntime/src/rt/deh.d",
    "druntime/src/rt/deh_win32.d",
    "druntime/src/rt/deh_win64_posix.d",
    "druntime/src/rt/dso.d",
    "druntime/src/rt/ehalloc.d",
    "druntime/src/rt/invariant.d",
    "druntime/src/rt/llmath.d",
    "druntime/src/rt/memory.d",
    "druntime/src/rt/memset.d",
    "druntime/src/rt/minfo.d",
    "druntime/src/rt/msvc.d",
    "druntime/src/rt/msvc_math.d",
    "druntime/src/rt/profilegc.d",
    "druntime/src/rt/sections_android.d",
    "druntime/src/rt/sections_darwin_64.d",
    "druntime/src/rt/sections_ldc.d",
    "druntime/src/rt/sections_osx_x86.d",
    "druntime/src/rt/sections_osx_x86_64.d",
    "druntime/src/rt/sections_solaris.d",
    "druntime/src/rt/sections_win32.d",
    "druntime/src/rt/sections_win64.d",
    "druntime/src/rt/tlsgc.d",
    "druntime/src/rt/trace.d",
    "druntime/src/rt/util/typeinfo.d",
    "druntime/src/rt/util/utility.d",
    "druntime/src/rt/aaA.d",
    "druntime/src/rt/alloca.d",
    "druntime/src/rt/cover.d",
    "druntime/src/rt/dmain2.d",
    "druntime/src/rt/dwarfeh.d",
    "druntime/src/rt/lifetime.d",
    "druntime/src/rt/monitor_.d",
    "druntime/src/rt/sections.d",
    "druntime/src/rt/sections_elf_shared.d",
    "druntime/src/rt/tracegc.d",
    "druntime/src/test_runner.d",
};

fn buildZlib(b: *std.Build, options: buildOptions) *std.Build.Step.Compile {
    const phobos_path = if (options.dependency) |dep|
        dep.path("").getPath(b)
    else
        unreachable;
    const phobos_zlib_path = b.pathJoin(&.{ phobos_path, "etc", "c", "zlib" });
    const libz = b.addStaticLibrary(.{
        .name = "z",
        .target = options.target,
        .optimize = options.optimize,
    });
    libz.pie = true;

    libz.addIncludePath(.{ .cwd_relative = phobos_zlib_path });
    libz.addCSourceFiles(.{
        .root = .{ .cwd_relative = phobos_zlib_path },
        .files = &.{
            "adler32.c",
            "crc32.c",
            "deflate.c",
            "infback.c",
            "inffast.c",
            "inflate.c",
            "inftrees.c",
            "trees.c",
            "zutil.c",
            "compress.c",
            "uncompr.c",
            "gzclose.c",
            "gzlib.c",
            "gzread.c",
            "gzwrite.c",
        },
        .flags = &.{
            "-std=c89",
            "-Wall",
            "-Wextra",
            "-Wno-unused-parameter",
        },
    });
    libz.linkLibC();
    return libz;
}
