name: Zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-master
      - name: Build Summary
        run: zig build -Dlinkage=dynamic -Dphobos --summary all -freference-trace
